version: "3.9"
services:
  exchanger:
    image: currency-exchngr_exchanger
    build: .
    restart: on-failure
    ports:
      - 8088:8088
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db

  db:
    image: postgres:14
    restart: on-failure
    environment:
      POSTGRES_DB: currency_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
volumes:
  postgresql-volume:
    external: true

