version: "3.9"
services:
  exchanger:
    build: .
    restart: on-failure
    ports:
      - '8088:8088'
    environment:
      API_URL: http://api:8006/rates/
      POSTGRES_HOST: db
      POSTGRES_DB: currency_rates
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
      - api
  db:
    image: postgres:14
    restart: on-failure
    environment:
      POSTGRES_DB: currency_rates
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  api:
    image: kegisa/currency-service
    restart: on-failure
    expose:
      - 8007
    ports:
      - 8007:8006
