version: "3.9"
services:
  currency-exchgr:
    build: ./
    restart: "no"
    ports:
      - 8088:8088
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: on-failure
    environment:
      POSTGRES_DB: "currency_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "fedor"
      PGDATA: "/tmp"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
