server:
  port: 8088

spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

api:
  url: http://${API_URL}/

logging:
  level:
    com.andrey.currencyexchgr.repository.ApiCurrencyRepository: DEBUG
  file:
    name: logs/OpenFeign.log



